# @package _global_

model:
  base_model: lrast/angle_extraction_pretrained

train:
  lr: 1.0e-06
  run_name: sweep
  max_epochs: 30
  frozen_base: False

hydra:
  mode: MULTIRUN
  sweep:
    dir: experiments/multirun/${now:%Y-%m-%d\(%H:%M:%S\)}_loss_sweep
    subdir: ${hydra.job.num}_kappa_${data.kappa}_loss_${model.loss_name}
  sweeper:
    params:
      data.kappa: 0.01, 1., 10.
      model.loss_name: angle_diff, sq_diff, sqrt_diff
